# Generated by Django 4.1.3 on 2022-11-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='channels',
            field=models.ManyToManyField(related_name='channels', to='channel.channel'),
        ),
    ]
